apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: chord-nodes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
      nodePort: 30011
  type: NodePort  # Expose via a NodePort to access externally
